apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-autenticacion-postgres
  annotations:
    # ACÁ VA EL ARN DEL ROL QUE CREASTE EN AWS
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/rol-serviceAccount-postgres
