name: Worker - CI Docker build and Push

on:
  push:
    branches:
      - main
    paths:
      - "worker/**"  
  pull_request:
    branches:
      - main
    paths:
      - "worker/**" 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v2
      - name: Log in to DockerHub

        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./worker                          # !!!!!!!!!!!!! carpeta con el Dockerfile !!!!!!!!!!!!!!!!!!!
          push: ${{ github.event_name == 'push' }} # solo pushea en push a main, no en PR
          tags: |
            ${{ secrets.DOCKERHUB_NAME }}/app-worker:latest              
            ${{ secrets.DOCKERHUB_NAME }}/app-worker:${{ github.sha }} 
        ## Arma la imagen con el tag "latest" y con el tag del commit SHA, y pushea a DockerHub si es un push a main, no en PR
      - name: Update GitOps Repository
        # Solo actualizamos el repo de GitOps si la construcción en DockerHub fue exitosa
        run: |
          # 1. Clonar el repositorio de GitOps usando el token personal (PAT)
          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/AgustinLandriel/gitops-voting-app.git
          cd gitops-voting-app
          
          # 2. Configurar usuario de Git para el commit automático
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
          # 3. Reemplazar el tag de la imagen en el archivo YAML usando sed
          sed -i "s|image: ${{ secrets.DOCKERHUB_NAME }}/app-worker:.*|image: ${{ secrets.DOCKERHUB_NAME }}/app-worker:${{ github.sha }}|g" k8s/worker/worker.yaml
          
          # 4. Hacer commit y push del cambio
          git add .
          git commit -m "Update worker image tag to ${{ github.sha }}"
          git push origin main