name: CI Docker build and Push

on:
  push:
    branches:
      - main
    paths:
      - "vote/**"  
  pull_request:
    branches:
      - main
    paths:
      - "vote/**" 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v2
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./vote                          # !!!!!!!!!!!!! carpeta con el Dockerfile !!!!!!!!!!!!!!!!!!!
          push: ${{ github.event_name == 'push' }} # solo pushea en push a main, no en PR
          tags: |
            ${{ secrets.DOCKERHUB_NAME }}/app-vote:latest              
            ${{ secrets.DOCKERHUB_NAME }}/app-vote:${{ github.sha }} 
        ## Arma la imagen con el tag "latest" y con el tag del commit SHA, y pushea a DockerHub si es un push a main, no en PR